---
title: "explore_youngstock"
format: html
editor: source
format: 
 html:
   embed-resources: true
   toc: true
   toc-location: left
execute:
    echo: false
    message: false
    warning: false
---

```{r}
library(tidyverse)
library(arrow)
library(dtplyr)
library(DT)

source('functions/DT_base.R') #functions to parse remarks and protocols

events_formatted<-read_parquet('data/intermediate_files/events_formatted.parquet')

summarize_events<-events_formatted |> 
  group_by(event_type, event) |> 
  summarize(count_rows=sum(n()))|>
  ungroup()%>%
  mutate(event_type = factor(event_type), 
         Event = factor(event))

```

# Summary Graph

```{r}
facet_order <- summarize_events %>%
  group_by(event_type) %>%
  summarise(n_y = n_distinct(event)) %>%
  arrange(desc(n_y)) %>%  # Order by most y categories
  pull(event_type)

# order events
summarize_events <- summarize_events %>%
  mutate(event = fct_reorder(event, count_rows, .fun = sum, .desc = FALSE)) 

  ggplot(summarize_events)+
  geom_bar(aes(x = event,
               y = count_rows, fill = event_type), stat = "identity")+
  facet_wrap(factor(event_type, levels = facet_order) ~., scales = 'free')+
  coord_flip()+
  scale_fill_viridis_d()+
  theme_minimal()+
  labs(x = "",
       y = "Row Count")+
  theme(legend.position = "none",
        # axis.text.y = element_text(size = 6)
        )
```
