---
title: "Disease Template"
format: html
editor: source
---

```{r}
library(tidyverse)
library(arrow)
library(dtplyr)

source('functions/DT_base.R')

```

```{r}
animals<-read_parquet('data/intermediate_files/animals.parquet') #each row is an animal
animal_lactations<-read_parquet('data/intermediate_files/animal_lactations.parquet') #each row is an animal lactation

disease_animal_long<-read_parquet('data/intermediate_files/disease_animal_level_long.parquet')
disease_animal_wide<-read_parquet('data/intermediate_files/disease_animal_level_wide.parquet')

disease_lact_long<-read_parquet('data/intermediate_files/disease_lactation_level_long.parquet')
disease_lact_wide<-read_parquet('data/intermediate_files/disease_lactation_level_wide.parquet')

```

## Eiligibility
```{r}

calander<-tibble(
  calander_date = seq.Date(from = min(disease_lact_long$date_disease_first), 
                           to = max(disease_lact_long$date_disease_last), 
                           by = 'day')
)

vwp = 75

eligible<-animal_lactations%>%
  left_joint(animals)%>%
  mutate(date_end_elig_to_breed = date_fresh)%>%
  mutate(elig_start = date_fresh + days(vwp),
         elig_end = case_when(
           is.na(date_died)<1~date_died,
           is.na(date_sold)<1~date_sold,
           is.na(date_dnb)<1~date_dnb,
           TRUE~date_fresh +days(200)
         ))



```



## 

### Calander Time
```{r}

disease_by_month<-disease_lact_long%>%
  mutate(repro_status = case_when(
    str_detect(list_treatments, 'A')~'Abort',
     str_detect(list_treatments, 'P|E')~'Pregnant',
    TRUE~'Open'
  ))%>%
  
  mutate(floordate_month = floor_date(date_disease_first, 'month'))%>%
  group_by(floordate_month)%>%
  mutate(disease_total = n_distinct(gap1_key), 
         cowlact_total = n_distinct(id_animal_lact))%>%
  ungroup()%>%
  group_by(floordate_month, disease_total, cowlact_total, repro_status)%>%
  summarise(ct_disease = n_distinct(gap1_key), 
            ct_cowlact = n_distinct(id_animal_lact))%>%
  ungroup()%>%
  mutate(pct_disease = ct_disease/disease_total,
         pct_cowlact = ct_cowlact/cowlact_total)





```

#### plot canander time
```{r}
ggplot(disease_by_month)+
  geom_point(aes(x = floordate_month, y = pct_disease, color = repro_status))+
  geom_smooth(aes(x = floordate_month, y = pct_disease, color = repro_status, group = repro_status), span = .2)+
  theme_bw()
```


### Phase Time (days in milk)
```{r}



```

# Disease Outcome



